## Our libraries that we are importing:

In [1]:
# 1. Importing all the libraries necessary for this assignment
import numpy as np
import pandas as pd
from scipy import stats

For this task, we will be using the famous Iris dataset, which includes measurements of 3 different species of Iris. Unfortunately, the download file was corrupted, viewed and saved in the wrong format, lost some data when transferred from MacOS to Windows, and someone accidentally spilled coffee on it. Fortunately, we believe the bulk of the data is still there. Our task will be to clean and transform the data (i.e., feature engineer) into a format that can be analyzed.

## Dataset:

First up, let's retrieve the data available from the damaged file.

In [2]:
# 2. Retrieving data from the damaged Excel file
print('-------------------------------- 2a ------------------------------')
df = pd.read_excel("messed_up_iris.xlsx")

# 2a. Showing the shape of the data
df.shape

-------------------------------- 2a ------------------------------

(150, 8)

In [3]:
# 2b. Showing the head of the data
print('-------------------------------- 2b ------------------------------')
df.head()

-------------------------------- 2b ------------------------------

   Unnamed: 0  sepal_length  sepal_width  ...  species   color  origin
0           0           5.1          3.5  ...   setosa   green     usa
1           1           4.9          3.0  ...   setosa  yellow     usa
2           2           4.7          3.2  ...   setosa   green     usa
3           3           4.6          3.1  ...   setosa  orange   japan
4           4           5.0          3.6  ...   setosa    blue  europe

[5 rows x 8 columns]

In [4]:
# 2c. Removing the extra index column
print('-------------------------------- 2c ------------------------------')
df = df.set_index('Unnamed: 0')

df.head()

-------------------------------- 2c ------------------------------

            sepal_length  sepal_width  petal_length  ...  species   color  origin
Unnamed: 0                                           ...
0                    5.1          3.5           1.4  ...   setosa   green     usa
1                    4.9          3.0           1.4  ...   setosa  yellow     usa
2                    4.7          3.2           1.3  ...   setosa   green     usa
3                    4.6          3.1           1.5  ...   setosa  orange   japan
4                    5.0          3.6           1.4  ...   setosa    blue  europe

[5 rows x 7 columns]

Now that we've retrieved the damaged Excel file, let's see what we can do to clean it up.

## Data cleaning:

We have a lot of missing data here. Let's start by removing the columns and rows where there are more than 50% of the data missing.

In [5]:
# 3. Removing more than 50% missing data
# 3a. Removing columns with more than 50% missing data
print('-------------------------------- 3a ------------------------------')
threshold = len(df) * .50
df = df.dropna(thresh=threshold, axis=1)

df.shape

-------------------------------- 3a ------------------------------

(150, 6)

In [6]:
# 3b. Removing rows with more than 50% missing data
print('-------------------------------- 3b ------------------------------')
# We have 6 columns, so now we drop rows where 50% data is missing, so we'll filter out
# rows that have missing values in 3 or more columns
df = df.dropna(thresh=df.shape[1]-3)

df.shape

-------------------------------- 3b ------------------------------

(145, 6)

Next, we'll remove duplicate data, if there is any.

In [7]:
# 4. Removing all possible duplicate rows based on all columns
print('--------------------------------- 4 ------------------------------')
df = df.drop_duplicates()

df.shape

--------------------------------- 4 ------------------------------

(140, 6)

Great! We'll go ahead and dummy code the categorical data.

In [8]:
# 5. Dummy coding the categorical data
print('--------------------------------- 5 ------------------------------')
df = pd.get_dummies(df, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species', 'origin'], drop_first=True, prefix=['SepalL', 'SepalW', 'PetalL', 'PetalW', 'Species', 'Origin'])

df.head()

--------------------------------- 5 ------------------------------

            SepalL_4.4  SepalL_4.5  ...  Origin_uas  Origin_usa
Unnamed: 0                          ...
0                    0           0  ...           0           1
1                    0           0  ...           0           1
2                    0           0  ...           0           1
3                    0           0  ...           0           0
4                    0           0  ...           0           0

[5 rows x 137 columns]

Now we will drop the redundant columns from the dataframe so that we are left with just the dummy coded columns.

In [9]:
# 6. Dropping redundant columns
print('--------------------------------- 6 ------------------------------')
df = df.T.drop_duplicates().T

df.head()

--------------------------------- 6 ------------------------------

            SepalL_4.4  SepalL_4.5  ...  Origin_uas  Origin_usa
Unnamed: 0                          ...
0                    0           0  ...           0           1
1                    0           0  ...           0           1
2                    0           0  ...           0           1
3                    0           0  ...           0           0
4                    0           0  ...           0           0

[5 rows x 130 columns]

Time to remove outliers above 2 standard deviations.

In [14]:
# 7. Removing outliers above 2 standard deviations
print('--------------------------------- 7 ------------------------------')
# I had some difficulty figuring out how to remove the outliers using z-scores...
df['z_score']=stats.zscore(df['data'])

--------------------------------- 7 ------------------------------

KeyError: ignored

Lastly, for the remaining missing data, we'll replace them with the median value.

In [15]:
# 8. Replacing missing data with the median value
print('--------------------------------- 8 ------------------------------')
df.fillna(df.median())

df.head()

--------------------------------- 8 ------------------------------

            SepalL_4.4  SepalL_4.5  ...  Origin_uas  Origin_usa
Unnamed: 0                          ...
0                    0           0  ...           0           1
1                    0           0  ...           0           1
2                    0           0  ...           0           1
3                    0           0  ...           0           0
4                    0           0  ...           0           0

[5 rows x 130 columns]

## Final dataset:

Here is our new dataset.

In [16]:
# 10. Printing our new dataset
print('-------------------------------- 10 ------------------------------')
print(df)

-------------------------------- 10 ------------------------------
            SepalL_4.4  SepalL_4.5  ...  Origin_uas  Origin_usa
Unnamed: 0                          ...
0                    0           0  ...           0           1
1                    0           0  ...           0           1
2                    0           0  ...           0           1
3                    0           0  ...           0           0
4                    0           0  ...           0           0
...                ...         ...  ...         ...         ...
145                  0           0  ...           0           0
146                  0           0  ...           0           0
147                  0           0  ...           0           0
148                  0           0  ...           0           0
149                  0           0  ...           0           1

[140 rows x 130 columns]

In [17]:
df.describe()

       SepalL_4.4  SepalL_4.5  SepalL_4.6  ...  Origin_japan  Origin_uas  Origin_usa
count  140.000000  140.000000  140.000000  ...    140.000000  140.000000  140.000000
mean     0.014286    0.007143    0.028571  ...      0.300000    0.014286    0.350000
std      0.119092    0.084515    0.167197  ...      0.459903    0.119092    0.478682
min      0.000000    0.000000    0.000000  ...      0.000000    0.000000    0.000000
25%      0.000000    0.000000    0.000000  ...      0.000000    0.000000    0.000000
50%      0.000000    0.000000    0.000000  ...      0.000000    0.000000    0.000000
75%      0.000000    0.000000    0.000000  ...      1.000000    0.000000    1.000000
max      1.000000    1.000000    1.000000  ...      1.000000    1.000000    1.000000

[8 rows x 130 columns]